version: '2'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - ./src:/code
        restart: always
    redis:
        image: "redis:alpine"
        restart: always
